Added basic models
Ryu4fly/scheduler-backend pull request #1
Opened 2022-02-27 02:52 UTC by Ryu4fly

2022-03-05 03:33 UTC, loucho requested changes

2022-03-05 03:33 UTC, loucho commented on scheduler/migrations/0001_initial.py
> +                ('created', models.DateTimeField(auto_now_add=True)),
aside from `created` it's always useful to include an `updated` field that is automatically updated every time there is a change in the record 
In mysql you can configure like this [DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP](https://dev.mysql.com/doc/refman/8.0/en/timestamp-initialization.html), but you would have to check the django way to specify it

2022-03-05 03:33 UTC, loucho commented on scheduler/migrations/0001_initial.py
> +            fields=[
This needs 1 more field to put the status (like Pending, Accepted, etc)
I recommend using a tinyint field type since I don't think there will be a lot of different statuses

2022-03-05 03:33 UTC, loucho commented on scheduler/models.py
> +from django.db import models
Probably this was a better place to put the comments I put in the migrations :P

2022-03-06 12:52 UTC, Ryu4fly commented on scheduler/migrations/0001_initial.py
> +                ('created', models.DateTimeField(auto_now_add=True)),
https://simpleisbetterthancomplex.com/tips/2016/05/23/django-tip-4-automatic-datetime-fields.html

2022-03-06 12:54 UTC, Ryu4fly commented on scheduler/migrations/0001_initial.py
> +            fields=[
https://docs.djangoproject.com/en/4.0/ref/models/fields/#choices

2022-03-06 14:00 UTC, loucho approved these changes
Looks good 👍🏼

2022-03-06 15:02 UTC, merged